<a href="https://colab.research.google.com/github/Sakalya100/MLDLS2021/blob/main/Classification_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/sample_data/jobclassinfo2.csv')
print(dataset)

    ID  JobFamily  JobClass  ...  FinancialBudget    PG    JobFamilyDescription
0    1          1         1  ...                5  PG05  Accounting And Finance
1    2          1         2  ...                7  PG06  Accounting And Finance
2    3          1         3  ...               10  PG08  Accounting And Finance
3    4          1         4  ...               11  PG10  Accounting And Finance
4    5          2         5  ...                1  PG01  Administrative Support
..  ..        ...       ...  ...              ...   ...                     ...
61  62         15        62  ...                1  PG03         Systems Analyst
62  63         15        63  ...                4  PG05         Systems Analyst
63  64         15        64  ...                5  PG06         Systems Analyst
64  65         15        65  ...                7  PG08         Systems Analyst
65  66         15        66  ...               11  PG10         Systems Analyst

[66 rows x 13 columns]


In [ ]:
dataset['JobFamilyDescription'] = dataset['JobFamilyDescription'].astype('category')
dataset['Encoded_Category'] = dataset['JobFamilyDescription'].cat.codes
print(dataset)

    ID  JobFamily  JobClass  ...    PG    JobFamilyDescription  Encoded_Category
0    1          1         1  ...  PG05  Accounting And Finance                 0
1    2          1         2  ...  PG06  Accounting And Finance                 0
2    3          1         3  ...  PG08  Accounting And Finance                 0
3    4          1         4  ...  PG10  Accounting And Finance                 0
4    5          2         5  ...  PG01  Administrative Support                 1
..  ..        ...       ...  ...   ...                     ...               ...
61  62         15        62  ...  PG03         Systems Analyst                14
62  63         15        63  ...  PG05         Systems Analyst                14
63  64         15        64  ...  PG06         Systems Analyst                14
64  65         15        65  ...  PG08         Systems Analyst                14
65  66         15        66  ...  PG10         Systems Analyst                14

[66 rows x 14 columns]


In [ ]:
X = dataset.iloc[:,0:11].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X.shape, Y.shape)

(66, 11) (66,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print(X_train.shape, X_test.shape)

(52, 11) (14, 11)


In [ ]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

[ 7 10 14 14  6 12  7  6  7 12 11  5  3  9] [ 7 10 11 11  4 14  8  6  9 14 14  7  3  7]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0 2 0 0]]
Accuracy:
 0.2857142857142857
Precision:
 [1.         0.         0.         1.         0.33333333 0.
 0.         1.         0.         0.         0.        ]
Recall:
 [1.         0.         0.         0.5        0.33333333 0.
 0.         1.         0.         0.         0.        ]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0]
 [0 0 1 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1]]
Accuracy:
 0.35714285714285715


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix:
 [[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2]]
Accuracy:
 0.7142857142857143


In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 1 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 2]]
Accuracy:
 0.6428571428571429
